title: Afterlife Song
author:
  name: Sifer Aseph
  email: siferaseph@protonmail.com

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate

minima:
  skin: auto
  
  date_format: "%B %-d, %Y"
  
  social_links:
    - { platform: telegram,       user_url: "http://t.me/cassandriel" }
    - { platform: github,         user_url: "https://github.com/sif" }
    - { platform: linkedin,       user_url: "https://www.linkedin.com/in/sifer-aseph/" }

show_excerpts: false

paginate: 30

markdown: kramdown
